Walker2DBulletEnv-v0: &base_config
  env_name: Walker2DBulletEnv-v0
  epochs: 1000
  record_interval: 10
  render: False
  training: True
  summary_dir: summaries/pybullet
  include: [pybullet_envs]
  algo: 
    name: sac
    kwargs: &algo_configs
      num_gradient_steps: 500
      num_init_exp_samples: 2000
      max_init_exp_timestep: auto
      tau: 0.0005
      update_interval: 1
      batch_size_kwargs:
        type: ConstantScheduler
        value: 64
      gamma_kwargs:
        type: ConstantScheduler
        value: 0.99
      q_lr_kwargs:
        type: ConstantScheduler
        value: 0.0003
      alpha_lr_kwargs:
        type: ConstantScheduler
        value: 0.0003
  policy:
    name: gaussian
    kwargs: &policy_configs
      mu_range: [-2.0, 2.0]
      log_std_range: [-20.0, 0.3]
      lr_kwargs:
        type: ConstantScheduler
        value: 0.0003