Discrete: &base_config
  env_name: LunarLander-v2
  epochs: 1000
  record_interval: 10
  render: False
  training: True
  load_model: null
  summary_dir: summaries/box2d
  algo:
    name: a2c
    kwargs: &algo_configs
      num_train: 2
      gamma_kwargs:
        type: ConstantScheduler
        value: 0.997
      lr_kwargs:
        type: ConstantScheduler
        value: 0.001
  policy:
    name: discrete
    kwargs:
      clip_norm: 5.0
      lr_kwargs:
        type: ConstantScheduler
        value: 0.001

Continuous:
  <<: *base_config
  env_name: LunarLanderContinuous-v2
  algo:
    name: a2c
    kwargs: *algo_configs
  policy:
    name: gaussian
    kwargs:
      mu_range: [-2.0, 2.0]
      log_std_range: [-20, 0.3]
      lr_kwargs:
        type: ConstantScheduler
        value: 0.001