CartPole-v1: &base_config
  env_name: CartPole-v1
  epochs: 1000
  record_interval: 10
  render: False
  summary_dir: summaries/classic_control
  algo:
    name: ddqn
    kwargs: &algo_configs
      clip_norm: 5.0
      num_gradient_steps: 25
      num_init_exp_samples: null
      batch_size_kwargs:
        type: ConstantScheduler
        value: 32
      gamma_kwargs:
        type: ConstantScheduler
        value: 0.9
      lr_kwargs:
        type: ConstantScheduler
        value: 0.0003
  policy:
    name: greedy_epsilon
    kwargs: &policy_configs
      eps_kwargs:
        type: ExpScheduler
        decay_rate: 0.01
        update_step: 20
        clip_range: [0.01, 0.5]

ignore_MountainCar-v0:
  <<: *base_config
  env_name: MountainCar-v0
  algo:
    name: dqn
    kwargs:
      <<: *algo_configs
      num_init_exp_samples: 1000
      gamma_kwargs:
        type: ConstantScheduler
        value: 0.997
  policy:
    name: greedy_epsilon
    kwargs: *policy_configs

ignore_LunarLander-v2:
  <<: *base_config
  env_name: LunarLander-v2
  summary_dir: summaries/box2d
  algo:
    name: dqn
    kwargs:
      <<: *algo_configs
      gamma_kwargs:
        type: ConstantScheduler
        value: 0.997

ignore_Acrobot-v1:
  <<: *base_config
  env_name: Acrobot-v1
  algo:
    name: dqn
    kwargs:
      <<: *algo_configs
      num_init_exp_samples: 1000
