default_Discrete: &base_config
  env_name: CartPole-v1
  epochs: 1000
  record_interval: 10
  render: False
  training: True
  summary_dir: temp
  algo:
    name: reinforce
    kwargs: &algo_configs
      alpha: 0.0003
      num_gradient_steps: 2
      gamma_kwargs:
        type: ConstantScheduler
        value: 0.9
  policy:
    name: discrete
    kwargs:
      clip_norm: 5.0
      lr_kwargs:
        type: ConstantScheduler
        value: 0.003
      layers:
        - {type: Dense, units: 100, kernel_regularizer: l2}
        - {type: LayerNormalization}
        - {type: Activation, activation: relu}
        - {type: Dense, units: 100, kernel_regularizer: l2}
        - {type: LayerNormalization}
        - {type: Activation, activation: relu}
        - {type: Dense, units: 1, activation: softmax}

Continuous:
  <<: *base_config
  env_name: LunarLanderContinuous-v2
  summary_dir: summaries/box2d
  algo:
    name: reinforce
    kwargs: *algo_configs
  policy:
    name: gaussian
    kwargs:
      clip_norm: 5.0
      mu_range: [-2.0, 2.0]
      log_std_range: [-20, 0.3]
      lr_kwargs:
        type: ConstantScheduler
        value: 0.001

      layers:
        - {type: Dense, units: 100, kernel_regularizer: l2}
        - {type: LayerNormalization}
        - {type: Activation, activation: relu}
        - {type: Dense, units: 100, kernel_regularizer: l2}
        - {type: LayerNormalization}
        - {type: Activation, activation: relu}
        - {type: Dense, units: 1}