default_HalfCheetah: &base_config
  env_name: HalfCheetah-v2
  epochs: 2
  record_interval: 10
  render: False
  summary_dir: summaries/mujoco
  algo: 
    name: sac
    kwargs: &algo_configs
      num_gradient_steps: auto
      num_init_exp_samples: 2000
      max_init_exp_timestep: auto
      tau: 0.005
      update_interval: 10
      num_q_nets: 2
      auto_ent: True
      target_entropy: auto
      init_log_alpha: 0.0
      batch_size_kwargs:
        type: ExpScheduler
        update_step: 50
        decay_rate: 0.001
        e_offset: 1.0
        e_scale: -1.0
        clip_range: [32, 256]
      gamma_kwargs:
        type: ConstantScheduler
        value: 0.997
      q_lr_kwargs:
        type: ConstantScheduler
        value: 0.0005
      alpha_lr_kwargs:
        type: ConstantScheduler
        value: 0.0005
  policy:
    name: gaussian
    kwargs: &policy_configs
      clip_norm: null
      learn_std: True
      mu_range: [-2.0, 2.0]
      log_std_range: [-20.0, 0.3]
      lr_kwargs:
        type: ConstantScheduler
        value: 0.0005


default_Hopper:
  <<: *base_config
  env_name: Hopper-v2
  algo:
    name: sac
    kwargs: 
      <<: *algo_configs
      num_init_exp_samples: 10000


default_Walker2D:
  <<: *base_config
  env_name: Walker2d-v2
  algo:
    name: sac
    kwargs: 
      <<: *algo_configs
      num_init_exp_samples: 10000


Swimmer:
  <<: *base_config
  env_name: Swimmer-v2