name: openai_gym
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python=3.7.4
  - pip>=19.0
  - scikit-learn=0.21.3
  - scipy=1.3.2
  - tensorflow
  - tensorflow-probability
  - mpi4py
  - pip:
      - gym==0.17.0
      - beautifulsoup4
      - highway-env
      - Box2D
      - pyyaml
      - streamlit
