name: openai_gym
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - conda>=4.6
  - python=3.7.4
  - pip>=19.0
  - matplotlib=3.1.1
  - pandas=0.25.3
  - scikit-learn=0.21.3
  - scipy=1.3.2
  - tensorflow-gpu=2.1.0
  - tensorflow-estimator=2.1.0
  - tensorflow-probability=0.7.0
  - pip:
      - gym==0.17.0
      - beautifulsoup4==4.9.1
      - mpi4py==3.0.3
      - highway-env
      - Box2D
      - pyyaml
      - streamlit
