name: open_ai_gym
  channels:
    - conda-forge
    - defaults
  dependencies:
    - matplotlib=3.1.1
    - pandas=0.25.3
    - python=3.7.4
    - scikit-learn=0.21.3
    - scipy=1.3.2
    - tensorflow-gpu=1.15.0
    - pip:
        - gym==0.18.0
        - mujoco-py<2.1,>=2.0
        - atari-py==0.2.6
        - beautifulsoup4==4.9.1
        - box2d-py==2.3.8
        - pybullet==2.9.6
        - mpi4py==3.0.3
        - highway-env
