name: openai_gym
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - matplotlib=3.1.1
  - pandas=0.25.3
  - python=3.7.4
  - conda>=4.6
  - scikit-learn=0.21.3
  - scipy=1.3.2
  - tensorflow-gpu
  - pip:
      - gym>=0.18.0
      - beautifulsoup4==4.9.1
      - mpi4py==3.0.3
      - highway-env
