name: openai_gym
channels:
  - defaults
  - anaconda
dependencies:
  - python=3.7.4
  - pip>=19.0
  - mpi4py
  - tensorflow-gpu=2.1.0
  - tensorflow-estimator=2.1.0
  - tensorflow-probability=0.7.0
  - pip:
      - gym==0.17.0
      - beautifulsoup4
      - highway-env
      - Box2D
      - pyyaml
      - streamlit
      - pybullet
