name: openai_gym
channels:
  - defaults
  - anaconda
dependencies:
  - python=3.7.4
  - pip>=19.0
  - mpi4py
  - pip:
      - tensorflow==1.15.0
      - tensorflow-probability==0.6.0
      - gym==0.17.0
      - pyglet
      - beautifulsoup4
      - highway-env
      - Box2D
      - pyyaml
      - streamlit
