SAC_BipedalWalker:
  env_name: BipedalWalker-v3
  epochs: 5
  record_interval: 1
  training: True
  render: True
  algo: 
    name: sac
    kwargs:
      gamma: 0.99
      batch_size: 256
      num_init_exp_samples: 10000
      layer_units: [100, 100]
      tau: 0.005
      update_interval: 1
      q_lr: 0.003
      alpha_lr: 0.003
      auto_ent: True
      target_entropy: auto
      layer_kwargs: 
          activation: relu
  policy:
    name: gaussian
    kwargs:
      alpha: 0.0002
      lr: 0.003
      shift_scale: 1.5
      min_log_scale: -10
      max_log_scale: 0.69
      layer_units: [256, 256]
      layer_kwargs:
          activation: relu

SAC_Walker2DBulletEnv:
  env_name: Walker2DBulletEnv-v0
  epochs: 10
  record_interval: 1
  training: True
  render: False
  algo: 
    name: sac
    kwargs:
      gamma: 0.99
      batch_size: 256
      num_init_exp_samples: 10000
      layer_units: [100, 100]
      tau: 0.005
      update_interval: 1
      q_lr: 0.003
      alpha_lr: 0.003
      auto_ent: True
      target_entropy: auto
      layer_kwargs: 
          activation: relu
  policy:
    name: gaussian
    kwargs:
      alpha: 0.0002
      lr: 0.003
      shift_scale: 1.5
      min_log_scale: -10
      max_log_scale: 0.69
      layer_units: [ 256, 256 ]
      layer_kwargs:
        activation: relu