algo:
  kwargs:
    alpha_lr_kwargs:
      type: ConstantScheduler
      value: 0.0003
    auto_ent: true
    batch_size_kwargs:
      type: ConstantScheduler
      value: 64
    buffer_size: 1000000
    clip_norm: null
    gamma_kwargs:
      type: ConstantScheduler
      value: 0.99
    init_log_alpha: 0.0
    max_init_exp_timestep: auto
    num_gradient_steps: 1000
    num_init_exp_samples: 5000
    num_q_nets: 2
    q_lr_kwargs:
      type: ConstantScheduler
      value: 0.0003
    reward_scale: 1.0
    target_entropy: auto
    tau: 0.0005
    update_interval: 1
  name: sac
epochs: 3000
load_model: null
policy:
  kwargs:
    layers:
    - kernel_regularizer: l2
      type: Dense
      units: 100
    - type: LayerNormalization
    - activation: relu
      type: Activation
    - target_shape:
      - 10
      - 10
      type: Reshape
    - filters: 8
      kernel_size: 3
      type: Conv1D
    - type: LayerNormalization
    - activation: relu
      type: Activation
    - filters: 64
      kernel_size: 3
      type: Conv1D
    - type: LayerNormalization
    - activation: relu
      type: Activation
    - type: Flatten
    - kernel_regularizer: l2
      type: Dense
      units: 32
    - type: LayerNormalization
    - activation: relu
      type: Activation
    log_std_range:
    - -20.0
    - 0.3
    lr_kwargs:
      type: ConstantScheduler
      value: 0.0003
    mu_range:
    - -2.0
    - 2.0
  name: gaussian
seed: 7
