Ant-v2: &base_config
  env_name: Ant-v2
  epochs: 10
  record_interval: 10
  render: False
  summary_dir: summaries/mujoco
  algo: 
    name: sac
    kwargs: &algo_configs
      reward_scale: 0.5
      num_gradient_steps: 100
      num_init_exp_samples: 3000
      max_init_exp_timestep: auto
      tau: 0.005
      update_interval: 10
      batch_size_kwargs:
        type: ConstantScheduler
        value: 64
      gamma_kwargs:
        type: ConstantScheduler
        value: 0.99
      q_lr_kwargs:
        type: ConstantScheduler
        value: 0.001
      alpha_lr_kwargs:
        type: ConstantScheduler
        value: 0.001
  policy:
    name: gaussian
    kwargs: &policy_configs
      mu_range: [-2.0, 2.0]
      log_std_range: [-20.0, 0.3]
      lr_kwargs:
        type: ConstantScheduler
        value: 0.001