Exp1:
  env_name: CarRacing-v0
  epochs: 4
  record_interval: 2
  render: True
  load_model: null
  summary_dir: summaries
  algo:
    name: reinforce
    kwargs:
      gamma_kwargs:
        type: ConstantScheduler
        value: 0.99
  policy:
    name: gaussian
    kwargs: &policy_configs
      mu_range: [-2.0, 2.0]
      log_std_range: [-20, 0.3]
      lr_kwargs:
        type: ConstantScheduler
        value: 0.0003
      preprocessors:
        - - { type: Conv2D, filters: 32, kernel_size: 3, activation: relu}
          - { type: MaxPool2D }
          - { type: Conv2D, filters: 64, kernel_size: 3, activation: relu}
          - { type: MaxPool2D }
          - { type: Conv2D, filters: 128, kernel_size: 3, activation: relu}
          - { type: Flatten}