sac: &default-config
  env_name: HalfCheetah-v2 # Humanoid-v2
  epochs: 1000
  record_interval: 10
  render: False
  training: True
  load_model: null
  summary_dir: pybullet
  algo: 
    name: sac
    kwargs: &algo-kwargs
      reward_scale: 1.0
      batch_size: 100
      num_init_exp_samples: 10000
      tau: 0.001
      update_interval: 1
      num_q_nets: 3
      clip_norm: 5.0
      auto_ent: True
      target_entropy: auto
      init_log_alpha: 0.0
      gamma_kwargs:
        type: ConstantScheduler
        value: 0.99
      q_lr_kwargs:
        type: ConstantScheduler
        value: 0.0001
      alpha_lr_kwargs:
        type: ConstantScheduler
        value: 0.0001
  policy:
    name: gaussian
    kwargs: &policy-kwargs
      clip_norm: 5.0
      learn_std: True
      # std_value: 0.1
      mu_range: [-2.0, 2.0]
      log_std_range: [-20, 0.1]
      lr_kwargs:
        type: ConstantScheduler
        value: 0.0001