algo:
  kwargs:
    alpha_lr_kwargs:
      type: ConstantScheduler
      value: 0.001
    auto_ent: true
    batch_size_kwargs:
      type: ConstantScheduler
      value: 64
    buffer_size: 500000
    clip_norm: null
    gamma_kwargs:
      type: ConstantScheduler
      value: 0.99
    init_log_alpha: 0.0
    max_init_exp_timestep: auto
    num_gradient_steps: 1000
    num_init_exp_samples: 3000
    num_q_nets: 2
    q_lr_kwargs:
      type: ConstantScheduler
      value: 0.001
    reward_scale: 0.5
    target_entropy: auto
    tau: 0.005
    update_interval: 10
  name: sac
epochs: 1000
load_model: null
policy:
  kwargs:
    log_std_range:
    - -20.0
    - 0.3
    lr_kwargs:
      type: ConstantScheduler
      value: 0.001
    mu_range:
    - -2.0
    - 2.0
  name: gaussian
seed: 1
