default_Parking_SAC:
  env_name: parking-v0
  epochs: 1000
  record_interval: 10
  render: False
  summary_dir: highway
  include: [highway_env]
  algo: 
    name: sac
    kwargs:
      batch_size: 64
      max_episode_steps: 100
      num_gradient_steps: auto
      num_init_exp_samples: 1000
      max_init_exp_timestep: auto
      tau: 0.01
      update_interval: 20
      num_q_nets: 2
      auto_ent: True
      target_entropy: auto
      init_log_alpha: 0.0
      gamma_kwargs:
        type: ConstantScheduler
        value: 0.99
      q_lr_kwargs:
        type: ConstantScheduler
        value: 0.001
      alpha_lr_kwargs:
        type: ConstantScheduler
        value: 0.001
  policy:
    name: gaussian
    kwargs:
      # clip_norm: 5.0
      mu_range: [-2, 2]
      log_std_range: [-20.0, 0.3]
      lr_kwargs:
        type: ConstantScheduler
        value: 0.001

Parking_DDPG:
  env_name: parking-v0
  epochs: 1000
  record_interval: 10
  render: False
  training: True
  summary_dir: highway
  include: [highway_env]
  algo: 
    name: ddpg
    kwargs:
      batch_size: 64
      max_episode_steps: 100
      num_gradient_steps: auto
      num_init_exp_samples: 1000
      max_init_exp_timestep: auto
      tau: 0.005
      update_interval: 10
      rr_prob: 0.0
      rr_offset: 1.0
      rr_factor: 0.1
      sigma_kwargs:
        type: ExpScheduler
        decay_rate: 0.01
        update_step: 50
        clip_range: [0.001, 0.3]
      gamma_kwargs:
        type: ConstantScheduler
        value: 0.997
      lr_kwargs:
        type: ConstantScheduler
        value: 0.0003
  policy:
    name: continuous
    kwargs: &policy_configs
      lr_kwargs:
        type: ConstantScheduler
        value: 0.0003
